apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-access
subjects:
  - kind: ServiceAccount
    name: data-access
