apiVersion: v1
kind: Service
metadata:
  name: data-access
spec:
  type: NodePort
  selector:
    app: data-access
  ports:
    - protocol: TCP
      nodePort: {{ .Values.dataAccess.port }}
      port: 8080
      targetPort: 8080
