apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - protocol: TCP
      name: port1
      nodePort: {{ .Values.frontEnd.port }}
      port: {{ .Values.frontEnd.port }}
      targetPort: 8080