apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - protocol: TCP
      name: port1
      nodePort: 30033
      port: 30033
      targetPort: 8080