apiVersion: batch/v1
kind: Job
metadata:
  name: provisioning-app-job
spec:
  template:
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup data-mongodb-1.data-mongodb-headless.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for db; sleep 2; done"]
      containers:
        - name: provisioning-app
          image: provisioning-app:1.0.0
          command: ['java', '-cp', '/usr/src/app/*:/usr/src/app/dependency/*','com.test.mongodb.provision.ProvisioningApplication']
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
  backoffLimit: 4
